# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(default='', max_length=50)),
                ('number', models.CharField(default='', max_length=12)),
                ('email', models.CharField(default='', max_length=20)),
                ('building', models.CharField(default='', max_length=50)),
                ('st_one', models.CharField(default='', max_length=50)),
                ('st_two', models.CharField(default='', max_length=50)),
                ('area', models.CharField(default='', max_length=20)),
                ('state', models.CharField(default='', max_length=2)),
                ('zipcode', models.CharField(default='', max_length=5)),
                ('low', models.IntegerField(default=0)),
                ('high', models.IntegerField(default=0)),
                ('cost_notes', models.CharField(default='', max_length=50)),
                ('rooms', models.BooleanField(default=False)),
                ('studio', models.BooleanField(default=False)),
                ('one_br', models.BooleanField(default=False)),
                ('two_br', models.BooleanField(default=False)),
                ('three_br', models.BooleanField(default=False)),
                ('notes', models.CharField(default='', max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Apartments',
            },
        ),
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('individual', models.CharField(default='', max_length=50)),
                ('number', models.CharField(default='', max_length=12)),
                ('email', models.CharField(default='', max_length=20)),
                ('building', models.CharField(default='', max_length=50)),
                ('st_one', models.CharField(default='', max_length=50)),
                ('st_two', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=20)),
                ('state', models.CharField(default='', max_length=2)),
                ('zipcode', models.CharField(default='', max_length=5)),
                ('low', models.IntegerField(default=0)),
                ('high', models.IntegerField(default=0)),
                ('cost_notes', models.CharField(default='', max_length=50)),
                ('rooms', models.BooleanField(default=False)),
                ('studio', models.BooleanField(default=False)),
                ('one_br', models.BooleanField(default=False)),
                ('two_br', models.BooleanField(default=False)),
                ('three_br', models.BooleanField(default=False)),
                ('notes', models.CharField(default='', max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Apartments',
            },
        ),
    ]
