# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20170223_0131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landlord',
            options={'verbose_name_plural': 'Landlords'},
        ),
        migrations.AlterField(
            model_name='landlord',
            name='building',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='city',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='cost_notes',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='email',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='st_one',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='st_two',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='state',
            field=models.CharField(blank=True, default='MD', max_length=2),
        ),
    ]
