# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20170223_0139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landlord',
            old_name='individual',
            new_name='entity',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='agency',
        ),
        migrations.AddField(
            model_name='apartment',
            name='entity',
            field=models.CharField(default='', max_length=50),
        ),
    ]
