# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 03:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20170223_0239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='building',
        ),
        migrations.RemoveField(
            model_name='landlord',
            name='building',
        ),
    ]
