# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_auto_20170223_0302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='entity',
            new_name='agency',
        ),
        migrations.RenameField(
            model_name='landlord',
            old_name='entity',
            new_name='individual',
        ),
        migrations.RemoveField(
            model_name='landlord',
            name='cost_notes',
        ),
        migrations.AddField(
            model_name='apartment',
            name='building',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
