# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 01:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='agency',
            new_name='entity',
        ),
        migrations.RenameField(
            model_name='landlord',
            old_name='individual',
            new_name='entity',
        ),
    ]
