# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170413_0147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='building',
        ),
    ]
