# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-31 06:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_apartment_building'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(default='', max_length=50)),
                ('activity', models.CharField(default='', max_length=100)),
                ('end_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='(UTC)')),
            ],
            options={
                'verbose_name_plural': 'Logs',
            },
        ),
    ]
