# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-31 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='account',
            field=models.CharField(default='anonymous', max_length=50),
        ),
        migrations.AlterField(
            model_name='log',
            name='activity',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
