# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-31 07:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20170531_0658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='end_date',
            new_name='date',
        ),
    ]
