# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20170223_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='agency',
            field=models.CharField(default='', max_length=100),
        ),
    ]
